# Generated by Django 2.1.3 on 2019-11-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmstudio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filmstudio_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='1800x400')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='filmstudio_inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
