# Generated by Django 2.1.3 on 2019-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmstudio', '0002_filmstudio_img_filmstudio_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmstudio_inventory',
            name='desc',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='filmstudio_img',
            name='name',
            field=models.CharField(max_length=999, verbose_name='pildi nimi'),
        ),
        migrations.AlterField(
            model_name='filmstudio_inventory',
            name='item',
            field=models.CharField(blank=True, max_length=99, unique=True),
        ),
    ]
