# Generated by Django 2.1.3 on 2019-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmstudio', '0003_auto_20191101_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmstudio_inventory',
            name='qty',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
