# Generated by Django 2.1.3 on 2019-11-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmstudio', '0004_filmstudio_inventory_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmstudio_lang',
            name='header',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='filmstudio_lang',
            name='table_field1',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='filmstudio_lang',
            name='table_field2',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='filmstudio_lang',
            name='table_field3',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='filmstudio_lang',
            name='text',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='filmstudio_inventory',
            name='qty',
            field=models.CharField(blank=True, max_length=2, verbose_name='mitu tk'),
        ),
    ]
