# Generated by Django 2.2.9 on 2019-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmstudio', '0007_auto_20191103_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='firmstudio_vid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, verbose_name='video nimi')),
                ('url', models.CharField(max_length=999, verbose_name='video link')),
            ],
        ),
    ]
