# Generated by Django 2.2.9 on 2019-12-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmstudio', '0008_firmstudio_vid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='firmstudio_vid',
            new_name='filmstudio_vid',
        ),
    ]
