# Generated by Django 2.2.9 on 2019-12-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmstudio', '0009_auto_20191230_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmstudio_lang',
            name='videos',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
