# Generated by Django 2.2.9 on 2020-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0021_toode_toode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toode',
            name='toode_id',
            field=models.CharField(default='', max_length=999),
        ),
    ]
