# Generated by Django 2.2.9 on 2020-04-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0022_auto_20200406_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='toode',
            name='specs',
            field=models.TextField(blank=True),
        ),
    ]
