# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0002_google_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='google_link_toidupood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=999)),
            ],
        ),
    ]
