# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-28 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0003_google_link_toidupood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='google_link_toidupood',
        ),
    ]
