# Generated by Django 2.2.9 on 2020-04-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0004_delete_google_link_toidupood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kalender_entry',
        ),
    ]
