# Generated by Django 2.1.3 on 2019-11-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=3, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=99)),
                ('item_price', models.CharField(blank=True, max_length=99)),
            ],
        ),
    ]
