# Generated by Django 2.1.3 on 2019-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstore_lang',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodstore_lang',
            name='header',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='foodstore_lang',
            name='menu',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='foodstore_lang',
            name='table_field1',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AddField(
            model_name='foodstore_lang',
            name='table_field2',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_price',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
