# Generated by Django 2.1.3 on 2019-11-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0003_auto_20191101_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='lang',
            field=models.CharField(max_length=3),
        ),
    ]
