# Generated by Django 2.1.3 on 2019-11-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0005_auto_20191101_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_price',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
