# Generated by Django 2.1.3 on 2019-11-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0006_auto_20191102_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_cat',
            field=models.CharField(blank=True, max_length=99),
        ),
    ]
