# Generated by Django 2.1.3 on 2019-11-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0007_menu_item_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstore_lang',
            name='bg_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
