# Generated by Django 2.1.3 on 2019-11-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='menu_items',
        ),
    ]
