# Generated by Django 2.1.3 on 2019-11-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20191101_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='price',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
