# Generated by Django 2.1.3 on 2019-11-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20191101_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='price',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
