# Generated by Django 2.2.9 on 2020-04-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20191102_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menu_items',
        ),
        migrations.DeleteModel(
            name='menu_lang',
        ),
    ]
